import {Product} from './product';

export const MOCK_PRODUCTS: Product[] = [{"id":1,"name":"Cheese - Shred Cheddar / Mozza","category":"Health","quantity":8,"shortageQtyWarning":2,"active":false,"imgUrl":"http://dummyimage.com/171x205.png/ff4444/ffffff"},
{"id":2,"name":"Asparagus - White, Fresh","category":"Automotive","quantity":7,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/172x126.png/ff4444/ffffff"},
{"id":3,"name":"Cheese - Taleggio D.o.p.","category":"Automotive","quantity":10,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/111x192.png/ff4444/ffffff"},
{"id":4,"name":"Bread - Hot Dog Buns","category":"Shoes","quantity":10,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/210x110.png/ff4444/ffffff"},
{"id":5,"name":"Vaccum Bag 10x13","category":"Beauty","quantity":2,"shortageQtyWarning":4,"active":true,"imgUrl":"http://dummyimage.com/100x208.png/ff4444/ffffff"},
{"id":6,"name":"Apple - Delicious, Golden","category":"Outdoors","quantity":10,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/121x211.png/dddddd/000000"},
{"id":7,"name":"Glass - Wine, Plastic, Clear 5 Oz","category":"Kids","quantity":6,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/183x117.png/dddddd/000000"},
{"id":8,"name":"Sage - Fresh","category":"Books","quantity":6,"shortageQtyWarning":2,"active":false,"imgUrl":"http://dummyimage.com/116x181.png/dddddd/000000"},
{"id":9,"name":"Soupfoamcont12oz 112con","category":"Grocery","quantity":8,"shortageQtyWarning":1,"active":false,"imgUrl":"http://dummyimage.com/106x102.png/ff4444/ffffff"},
{"id":10,"name":"Gherkin","category":"Industrial","quantity":2,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/164x194.png/ff4444/ffffff"},
{"id":11,"name":"Beans - Yellow","category":"Outdoors","quantity":4,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/233x197.png/cc0000/ffffff"},
{"id":12,"name":"Pasta - Rotini, Colour, Dry","category":"Home","quantity":3,"shortageQtyWarning":2,"active":false,"imgUrl":"http://dummyimage.com/119x114.png/ff4444/ffffff"},
{"id":13,"name":"Shiro Miso","category":"Music","quantity":9,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/181x159.png/dddddd/000000"},
{"id":14,"name":"Huck Towels White","category":"Movies","quantity":2,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/242x126.png/cc0000/ffffff"},
{"id":15,"name":"Liqueur - Melon","category":"Baby","quantity":6,"shortageQtyWarning":2,"active":false,"imgUrl":"http://dummyimage.com/149x250.png/dddddd/000000"},
{"id":16,"name":"Table Cloth 53x69 White","category":"Baby","quantity":3,"shortageQtyWarning":3,"active":false,"imgUrl":"http://dummyimage.com/228x122.png/5fa2dd/ffffff"},
{"id":17,"name":"Apple - Fuji","category":"Baby","quantity":1,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/212x207.png/cc0000/ffffff"},
{"id":18,"name":"Foil - Round Foil","category":"Grocery","quantity":1,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/220x222.png/5fa2dd/ffffff"},
{"id":19,"name":"Appetizer - Chicken Satay","category":"Toys","quantity":1,"shortageQtyWarning":3,"active":false,"imgUrl":"http://dummyimage.com/228x207.png/cc0000/ffffff"},
{"id":20,"name":"Chocolate - Pistoles, White","category":"Music","quantity":1,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/159x126.png/5fa2dd/ffffff"},
{"id":21,"name":"Eggs - Extra Large","category":"Sports","quantity":1,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/218x200.png/dddddd/000000"},
{"id":22,"name":"Oil - Canola","category":"Outdoors","quantity":4,"shortageQtyWarning":1,"active":false,"imgUrl":"http://dummyimage.com/214x238.png/cc0000/ffffff"},
{"id":23,"name":"Chocolate - Compound Coating","category":"Clothing","quantity":7,"shortageQtyWarning":3,"active":false,"imgUrl":"http://dummyimage.com/248x242.png/dddddd/000000"},
{"id":24,"name":"Plate Pie Foil","category":"Electronics","quantity":6,"shortageQtyWarning":3,"active":true,"imgUrl":"http://dummyimage.com/133x203.png/dddddd/000000"},
{"id":25,"name":"Veal - Nuckle","category":"Outdoors","quantity":7,"shortageQtyWarning":1,"active":false,"imgUrl":"http://dummyimage.com/106x149.png/dddddd/000000"},
{"id":26,"name":"Cake Sheet Combo Party Pack","category":"Music","quantity":1,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/172x111.png/dddddd/000000"},
{"id":27,"name":"Ecolab - Ster Bac","category":"Toys","quantity":9,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/202x223.png/dddddd/000000"},
{"id":28,"name":"Oil - Olive Bertolli","category":"Movies","quantity":4,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/184x221.png/5fa2dd/ffffff"},
{"id":29,"name":"Vacuum Bags 12x16","category":"Games","quantity":5,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/221x243.png/5fa2dd/ffffff"},
{"id":30,"name":"Soup - Knorr, Chicken Noodle","category":"Home","quantity":3,"shortageQtyWarning":4,"active":false,"imgUrl":"http://dummyimage.com/245x123.png/ff4444/ffffff"},
{"id":31,"name":"Lid - 16 Oz And 32 Oz","category":"Automotive","quantity":6,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/170x224.png/5fa2dd/ffffff"},
{"id":32,"name":"Chocolate - Milk Coating","category":"Electronics","quantity":7,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/111x193.png/cc0000/ffffff"},
{"id":33,"name":"Muffins - Assorted","category":"Sports","quantity":5,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/160x205.png/cc0000/ffffff"},
{"id":34,"name":"Pastry - French Mini Assorted","category":"Automotive","quantity":4,"shortageQtyWarning":4,"active":true,"imgUrl":"http://dummyimage.com/239x184.png/ff4444/ffffff"},
{"id":35,"name":"Syrup - Monin - Blue Curacao","category":"Books","quantity":7,"shortageQtyWarning":3,"active":true,"imgUrl":"http://dummyimage.com/232x216.png/5fa2dd/ffffff"},
{"id":36,"name":"Breakfast Quesadillas","category":"Tools","quantity":10,"shortageQtyWarning":4,"active":true,"imgUrl":"http://dummyimage.com/173x189.png/cc0000/ffffff"},
{"id":37,"name":"Amaretto","category":"Sports","quantity":9,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/130x205.png/5fa2dd/ffffff"},
{"id":38,"name":"Lettuce - Sea / Sea Asparagus","category":"Industrial","quantity":7,"shortageQtyWarning":4,"active":false,"imgUrl":"http://dummyimage.com/106x229.png/ff4444/ffffff"},
{"id":39,"name":"Shichimi Togarashi Peppeers","category":"Kids","quantity":2,"shortageQtyWarning":3,"active":true,"imgUrl":"http://dummyimage.com/237x239.png/5fa2dd/ffffff"},
{"id":40,"name":"French Kiss Vanilla","category":"Clothing","quantity":10,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/211x198.png/ff4444/ffffff"},
{"id":41,"name":"Soup - Knorr, Classic Can. Chili","category":"Toys","quantity":3,"shortageQtyWarning":2,"active":false,"imgUrl":"http://dummyimage.com/159x175.png/5fa2dd/ffffff"},
{"id":42,"name":"Sorrel - Fresh","category":"Grocery","quantity":10,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/149x157.png/cc0000/ffffff"},
{"id":43,"name":"Muffin Batt - Ban Dream Zero","category":"Shoes","quantity":3,"shortageQtyWarning":1,"active":true,"imgUrl":"http://dummyimage.com/132x141.png/dddddd/000000"},
{"id":44,"name":"Lamb Tenderloin Nz Fr","category":"Outdoors","quantity":3,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/131x127.png/dddddd/000000"},
{"id":45,"name":"Glove - Cutting","category":"Kids","quantity":6,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/203x182.png/cc0000/ffffff"},
{"id":46,"name":"C - Plus, Orange","category":"Industrial","quantity":5,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/250x196.png/cc0000/ffffff"},
{"id":47,"name":"Chocolate Bar - Reese Pieces","category":"Grocery","quantity":10,"shortageQtyWarning":5,"active":true,"imgUrl":"http://dummyimage.com/238x226.png/ff4444/ffffff"},
{"id":48,"name":"Crab - Blue, Frozen","category":"Health","quantity":10,"shortageQtyWarning":5,"active":false,"imgUrl":"http://dummyimage.com/210x125.png/5fa2dd/ffffff"},
{"id":49,"name":"Shrimp - 16 - 20 Cooked, Peeled","category":"Books","quantity":5,"shortageQtyWarning":3,"active":false,"imgUrl":"http://dummyimage.com/224x105.png/ff4444/ffffff"},
{"id":50,"name":"Dill - Primerba, Paste","category":"Music","quantity":1,"shortageQtyWarning":2,"active":true,"imgUrl":"http://dummyimage.com/214x199.png/5fa2dd/ffffff"}];
